channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=0.35
- notebook=5.7
- nbconvert=5.4
- widgetsnbextension=3.4
# Python Kernel
- ipykernel=5.1
- ipywidgets=7.4
- ipyleaflet=0.9
- matplotlib=3.1.0
- python=3.6
- seaborn=0.7
- pyyaml=3.13
- scipy=1.1.0
- astropy=3.0.4
- sunpy=1.0.1
# C++ Kernel
- xeus-cling=0.5.1
